<?php

namespace ConsoleBundle\Repository\Level1;

/**
 * FinvizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinvizRepository extends \Doctrine\ORM\EntityRepository
{
}
