<?php

namespace ConsoleBundle\Repository\Level1;

/**
 * IqfeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
