<?php

namespace ConsoleBundle\Repository\Level1;

/**
 * YahooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YahooRepository extends \Doctrine\ORM\EntityRepository
{
}
