<?php

namespace AppBundle\Repository\Feed;

/**
 * MainFinvizDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainFinvizDataRepository extends \Doctrine\ORM\EntityRepository
{
}
