<?php

namespace AppBundle\Repository\Feed;

/**
 * MainMinutePrevRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainMinutePrevRepository extends \Doctrine\ORM\EntityRepository
{
}
