<?php

namespace AppBundle\Repository\Feed;

/**
 * MainBasicDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainBasicDataRepository extends \Doctrine\ORM\EntityRepository
{
}
