<?php

namespace AppBundle\Repository\Feed;

/**
 * MainLevel1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainLevel1Repository extends \Doctrine\ORM\EntityRepository
{
}
