<?php

namespace AppBundle\Repository\Feed;

/**
 * MainPremarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainPremarketRepository extends \Doctrine\ORM\EntityRepository
{
}
