<?php

namespace AppBundle\Repository\Feed;

/**
 * MainEarningsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainEarningsRepository extends \Doctrine\ORM\EntityRepository
{
}
