<?php

namespace AppBundle\Repository\Feed;

/**
 * MainWeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainWeekRepository extends \Doctrine\ORM\EntityRepository
{
}
