<?php

namespace AppBundle\Repository\Feed;

/**
 * MainCompanyInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainCompanyInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
