<?php

namespace AppBundle\Form\Choices;


class FilterChoices
{

    const CHOICES = [

        'ORDER' => [],
        'ASC' => ['desc'=>'','asc'=>'1'],
        'ROW' => [
            '20'=>'20',
            '50'=>'',
            '100'=>'100',
            '200'=>'200'
        ],
        'PREMARKET' => [
            'no'=>'',
            'yes'=>'1'
        ],
 
//$atrp
        'ATR_PERCENT' => [
            "Any" => "",
            "Under 5%" => "l|5",
            "Under 10%" => "l|10",
            "Under 20%" => "l|20",
            "Under 25%" => "l|25",
            "Under 30%" => "l|30",
            "Under 50%" => "l|50",
            "Under 100%" => "l|100",
            "Under 200%" => "l|200",
            "Under 300%" => "l|300",
            "Over 5%" => "m|5",
            "Over 10%" => "m|10",
            "Over 15%" => "m|15",
            "Over 20%" => "m|20",
            "Over 25%" => "m|25",
            "Over 30%" => "m|30",
            "Over 35%" => "m|35",
            "Over 40%" => "m|40",
            "Over 45%" => "m|45",
            "Over 50%" => "m|50",
            "Over 100%" => "m|100",
            "Over 200%" => "m|200",
            "Over 300%" => "m|300",
            "Over 400%" => "m|400",
            "Over 500%" => "m|500"
        ],


//$sizeex
        'SIZE_ON_EXTREM' => [
            "Any" => "",
            "Bid size on daily High" => "1",
            "Bid size on daily Low" => "2",
            "Ask size on daily High'" => "3",
            "Ask size on daily Low" => "4"
        ],


//$sizeusvol
        'SIZE_US_VOLUME' => [
            "Any" => "",
            "1% of avg. volume" => "0.01",
            "2% of avg. volume" => "0.02",
            "3% of avg. volume" => "0.03",
            "4% of avg. volume" => "0.04",
            "5% of avg. volume" => "0.05",
            "6% of avg. volume" => "0.06",
            "7% of avg. volume" => "0.07",
            "8% of avg. volume" => "0.08",
            "9% of avg. volume" => "0.09",
            "10% of avg. volume" => "0.10",
            "15% of avg. volume" => "0.15"
        ],


//$keyfilter
        'KEY_FILTER_BY' => [
            "" => "Price",
            "High" => "hi",
            "Low" => "lo",
            "Bid" => "bid",
            "Ask" => "ask"
        ],


//$keylev
        'KEY_LEVEL' => [
            "00 c " => "1",
            "50 c " => "2",
            "25 c " => "3",
            "10,20,30,40,50,60,70,80,90 c " => "4",
            "15,25,35,45,65,75,85,95 c " => "5"
        ],


//$eyrange

        'KEY_RANGE' => [
            "Any" => "",
            "0-1c above or below level" => "1,1",
            "0-2c above or below level" => "2,2",
            "0-3c above or below level" => "3,3",
            "0-4c above or below level" => "4,4",
            "0-5c above or below level" => "5,5",
            "0-1c above  level" => "0,1",
            "0-2c above level" => "0,2",
            "0-3c above  level" => "0,3",
            "0-4c above  level" => "0,4",
            "0-5c above  level" => "0,5",
            "0-1c  below level" => "1,0",
            "0-2c  below level" => "2,0",
            "0-3c  below level" => "3,0",
            "0-4c  below level" => "4,0",
            "0-5c  below level" => "5,0"
        ],


//$rundown

        'RUN_DOWN' => [
            "Any" => "",
            "1 min down 10% of ATR" => "1",
            "1 min down 10% of Range" => "2",
            "1 min down 25% of ATR" => "3",
            "1 min down 25% of Range" => "4",
            "1 min down 50% of ATR" => "5",
            "1 min down 50% of Range" => "6",
            "1 min down 70% of ATR" => "7",
            "1 min down 70% of Range" => "8",
            "1 min down 90% of ATR" => "9",
            "1 min down 90% of Range" => "10",
            "5 min down 10% of ATR" => "11",
            "5 min down 10% of Range" => "12",
            "5 min down 25% of ATR" => "13",
            "5 min down 25% of Range" => "14",
            "5 min down 50% of ATR" => "15",
            "5 min down 50% of Range" => "16",
            "5 min down 70% of ATR" => "17",
            "5 min down 70% of Range" => "18",
            "5 min down 90% of ATR" => "19",
            "5 min down 90% of Range" => "20",
            "10 min down 10% of ATR" => "21",
            "10 min down 10% of Range" => "22",
            "10 min down 25% of ATR" => "23",
            "10 min down 25% of Range" => "24",
            "10 min down 50% of ATR" => "25",
            "10 min down 50% of Range" => "26",
            "10 min down 70% of ATR" => "27",
            "10 min down 70% of Range" => "28",
            "10 min down 90% of ATR" => "29",
            "10 min down 90% of Range" => "30",
            "15 min down 10% of ATR" => "31",
            "15 min down 10% of Range" => "32",
            "15 min down 25% of ATR" => "33",
            "15 min down 25% of Range" => "34",
            "15 min down 50% of ATR" => "35",
            "15 min down 50% of Range" => "36",
            "15 min down 70% of ATR" => "37",
            "15 min down 70% of Range" => "38",
            "15 min down 90% of ATR" => "39",
            "15 min down 90% of Range" => "40"
        ],


//$runup

        'RUN_UP' => [
            "Any" => "",
            "1 min up 10% of ATR" => "1",
            "1 min up 10% of Range" => "2",
            "1 min up 25% of ATR" => "3",
            "1 min up 25% of Range" => "4",
            "1 min up 50% of ATR" => "5",
            "1 min up 50% of Range" => "6",
            "1 min up 70% of ATR" => "7",
            "1 min up 70% of Range" => "8",
            "1 min up 90% of ATR" => "9",
            "1 min up 90% of Range" => "10",
            "5 min up 10% of ATR" => "11",
            "5 min up 10% of Range" => "12",
            "5 min up 25% of ATR" => "13",
            "5 min up 25% of Range" => "14",
            "5 min up 50% of ATR" => "15",
            "5 min up 50% of Range" => "16",
            "5 min up 70% of ATR" => "17",
            "5 min up 70% of Range" => "18",
            "5 min up 90% of ATR" => "19",
            "5 min up 90% of Range" => "20",
            "10 min up 10% of ATR" => "21",
            "10 min up 10% of Range" => "22",
            "10 min up 25% of ATR" => "23",
            "10 min up 25% of Range" => "24",
            "10 min up 50% of ATR" => "25",
            "10 min up 50% of Range" => "26",
            "10 min up 70% of ATR" => "27",
            "10 min up 70% of Range" => "28",
            "10 min up 90% of ATR" => "29",
            "10 min up 90% of Range" => "30",
            "15 min up 10% of ATR" => "31",
            "15 min up 10% of Range" => "32",
            "15 min up 25% of ATR" => "33",
            "15 min up 25% of Range" => "34",
            "15 min up 50% of ATR" => "35",
            "15 min up 50% of Range" => "36",
            "15 min up 70% of ATR" => "37",
            "15 min up 70% of Range" => "38",
            "15 min up 90% of ATR" => "39",
            "15 min up 90% of Range" => "40"
        ],


//$mpriceper
        'MIN_PRICE_PERCENT' => [
            "Any" => "",
            "Up & 5% or more of ATR" => "m|5",
            "Up & 10% or more of ATR" => "m|10",
            "Up & 20% or more of ATR" => "m|20",
            "Up & 25% or more of ATR" => "m|25",
            "Up & 30% or more of ATR" => "m|30",
            "Up & 50% or more of ATR" => "m|50",
            "Up & 60% or more of ATR" => "m|60",
            "Up & 70% or more of ATR" => "m|70",
            "Up & 80% or more of ATR" => "m|80",
            "Up & 90% or more of ATR" => "m|90",
            "UP & 100% or more of ATR" => "m|100",
            "Down & 5% or more of ATR" => "l|-5",
            "Down & 10% or more of ATR" => "l|-10",
            "Down & 20% or more of ATR" => "l|-20",
            "Down & 25% or more of ATR" => "l|-25",
            "Down & 30% or more of ATR" => "l|-30",
            "Down & 50% or more of ATR" => "l|-50",
            "Down & 60% or more of ATR" => "l|-60",
            "Down & 70% or more of ATR" => "l|-70",
            "Down & 80% or more of ATR" => "l|-80",
            "Down & 90% or more of ATR" => "l|-90",
            "Down & 100% or more of ATR" => "l|-100"
        ],

//$volper
        'MINUTE_VOLUME_PERCENT' => [
            "Any" => "",
            "1% or more of current volume" => "1",
            "2% or more of current volume" => "2",
            "3% or more of current volume" => "3",
            "4% or more of current volume" => "4",
            "5% or more of current volume" => "5",
            "10% or more of current volume" => "10",
            "15% or more of current volume" => "15",
            "20% or more of current volume" => "20",
            "25% or more of current volume" => "25",
            "30% or more of current volume" => "30",
            "40% or more of current volume" => "40",
            "50% or more of current volume" => "50",
            "60% or more of current volume" => "60",
            "70% or more of current volume" => "70",
            "80% or more of current volume" => "80",
            "90% or more of current volume" => "90"
        ],


//$unsize
        'UNUSUAL_SIZE' => [
            "Any" => "",
            "Unusual bid size" => "1",
            "Unusual ask size" => "2"
        ],


//$earnf
        'EARNING_DATE' => [
            "Any" => "",
            "Today" => "1",
            "Today BMO and Yesterday AMC" => "2",
            "Yesterday" => "3",
            "Tomorrow" => "4"
        ],


//$newhilo

        'NEW_HI_LO' => [
            "Any" => "",
            "New High" => "1",
            "New Low" => "2",
            "0$ - 0.01$ below High" => "3",
            "0$ - 0.02$ below High" => "4",
            "0$ - 0.03$ below High" => "5",
            "0$ - 0.05$ below High" => "6",
            "0$ - 0.10$ below High" => "7",
            "0$ - 0.01$ above Low" => "8",
            "0$ - 0.02$ above Low" => "9",
            "0$ - 0.03$ above Low" => "10",
            "0$ - 0.05$ above Low" => "11",
            "0$ - 0.10$ above Low" => "12"
        ],

//$fig
        'FIGURE' => [
            "Any" => "",
            "*.00$" => "1",
            "*.50$" => "3",
            "*.00$ + *.50$" => "3",
            "0.00$ - 0.01$ above or below *.00$ " => "4",
            "0.00$ - 0.02$ above or below *.00$ " => "5",
            "0.00$ - 0.03$ above or below *.00$ " => "6",
            "0.00$ - 0.05$ above or below *.00$ " => "7",
            "0.00$ - 0.10$ above or below *.00$ " => "8",
            "0.00$ - 0.01$ above or below *.50$ " => "9",
            "0.00$ - 0.02$ above or below *.50$ " => "10",
            "0.00$ - 0.03$ above or below *.50$ " => "11",
            "0.00$ - 0.05$ above or below *.50$ " => "12",
            "0.00$ - 0.01$ above or below *.00$ or *.50$ " => "13",
            "0.00$ - 0.02$ above or below *.00$ or *.50$ " => "14",
            "0.00$ - 0.03$ above or below *.00$ or *.50$ " => "15",
            "0.00$ - 0.05$ above or below *.00$ or *.50$ " => "16"
        ],


//$spread

        'SPREAD' => [
            "Any" => "",
            "Over 0.01" => "m|0.01",
            "Over 0.02" => "m|0.02",
            "Over 0.03" => "m|0.03",
            "Over 0.04" => "m|0.04",
            "Over 0.05" => "m|0.05",
            "Over 0.06" => "m|0.06",
            "Over 0.07" => "m|0.07",
            "Over 0.08" => "m|0.08",
            "Over 0.09" => "m|0.09",
            "Under 0.01" => "l|0.01",
            "Under 0.02" => "l|0.02",
            "Under 0.03" => "l|0.03",
            "Under 0.04" => "l|0.04",
            "Under 0.05" => "l|0.05",
            "Under 0.06" => "l|0.06",
            "Under 0.07" => "l|0.07",
            "Under 0.08" => "l|0.08",
            "Under 0.09" => "l|0.09",
            "Under 0.10" => "l|0.10",
            "Under 0.15" => "l|0.15",
            "Under 0.25" => "l|0.25"
        ],


//$earn_time

        'EARNING_TIME' => [
            "Any" => "",
            "Before market open" => "bmo",
            "After market closed" => "amc"
        ],


//$etf

        'ETF' => [
            "Any" => "",
            "Только акции (исключить фонды)" => "2",
            "Только фонды (ETF & CEF)" => "1"
        ],

//$ind =
        'INDUSTRY' => [
            "Any" => "",
            "Accident & Health Insurance" => "Accident and Health Insurance",
            "Advertising Agencies" => "Advertising Agencies",
            "Aerospace/Defense - Major Diversified" => "Aerospace/Defense - Major Diversified",
            "Aerospace/Defense Products & Services" => "Aerospace/Defense Products and Services",
            "Agricultural Chemicals" => "Agricultural Chemicals",
            "Air Delivery & Freight Services" => "Air Delivery and Freight Services",
            "Air Services, Other" => "Air Services, Other",
            "Aluminum" => "Aluminum",
            "Apparel Stores" => "Apparel Stores",
            "Appliances" => "Appliances",
            "Application Software" => "Application Software",
            "Asset Management" => "Asset Management",
            "Auto Dealerships" => "Auto Dealerships",
            "Auto Manufacturers - Major" => "Auto Manufacturers - Major",
            "Auto Parts" => "Auto Parts",
            "Auto Parts Stores" => "Auto Parts Stores",
            "Auto Parts Wholesale" => "Auto Parts Wholesale",
            "Basic Materials Wholesale" => "Basic Materials Wholesale",
            "Beverages - Brewers" => "Beverages - Brewers",
            "Beverages - Soft Drinks" => "Beverages - Soft Drinks",
            "Beverages - Wineries & Distillers" => "Beverages - Wineries and Distillers",
            "Biotechnology" => "Biotechnology",
            "Broadcasting - Radio" => "Broadcasting - Radio",
            "Broadcasting - TV" => "Broadcasting - TV",
            "Building Materials Wholesale" => "Building Materials Wholesale",
            "Business Equipment" => "Business Equipment",
            "Business Services" => "Business Services",
            "Business Software & Services" => "Business Software and Services",
            "Catalog & Mail Order Houses" => "Catalog and Mail Order Houses",
            "CATV Systems" => "CATV Systems",
            "Cement" => "Cement",
            "Chemicals - Major Diversified" => "Chemicals - Major Diversified",
            "Cigarettes" => "Cigarettes",
            "Cleaning Products" => "Cleaning Products",
            "Closed-End Fund - Debt" => "Closed-End Fund - Debt",
            "Closed-End Fund - Equity" => "Closed-End Fund - Equity",
            "Closed-End Fund - Foreign" => "Closed-End Fund - Foreign",
            "Communication Equipment" => "Communication Equipment",
            "Computer Based Systems" => "Computer Based Systems",
            "Computer Peripherals" => "Computer Peripherals",
            "Computers Wholesale" => "Computers Wholesale",
            "Confectioners" => "Confectioners",
            "Conglomerates" => "Conglomerates",
            "Consumer Services" => "Consumer Services",
            "Copper" => "Copper",
            "Credit Services" => "Credit Services",
            "Dairy Products" => "Dairy Products",
            "Data Storage Devices" => "Data Storage Devices",
            "Department Stores" => "Department Stores",
            "Diagnostic Substances" => "Diagnostic Substances",
            "Discount, Variety Stores" => "Discount, Variety Stores",
            "Diversified Communication Services" => "Diversified Communication Services",
            "Diversified Computer Systems" => "Diversified Computer Systems",
            "Diversified Electronics" => "Diversified Electronics",
            "Diversified Investments" => "Diversified Investments",
            "Diversified Machinery" => "Diversified Machinery",
            "Diversified Utilities" => "Diversified Utilities",
            "Drug Delivery" => "Drug Delivery",
            "Drug Manufacturers - Major" => "Drug Manufacturers - Major",
            "Drug Manufacturers - Other" => "Drug Manufacturers - Other",
            "Drug Related Products" => "Drug Related Products",
            "Drug Stores" => "Drug Stores",
            "Drugs - Generic" => "Drugs - Generic",
            "Drugs Wholesale" => "Drugs Wholesale",
            "Education & Training Services" => "Education and Training Services",
            "Electric Utilities" => "Electric Utilities",
            "Electronic Equipment" => "Electronic Equipment",
            "Electronics Stores" => "Electronics Stores",
            "Electronics Wholesale" => "Electronics Wholesale",
            "Entertainment - Diversified" => "Entertainment - Diversified",
            "Exchange Traded Fund" => "Exchange Traded Fund",
            "Farm & Construction Machinery" => "Farm and Construction Machinery",
            "Farm Products" => "Farm Products",
            "Food - Major Diversified" => "Food - Major Diversified",
            "Food Wholesale" => "Food Wholesale",
            "Foreign Money Center Banks" => "Foreign Money Center Banks",
            "Foreign Regional Banks" => "Foreign Regional Banks",
            "Foreign Utilities" => "Foreign Utilities",
            "Gaming Activities" => "Gaming Activities",
            "Gas Utilities" => "Gas Utilities",
            "General Building Materials" => "General Building Materials",
            "General Contractors" => "General Contractors",
            "General Entertainment" => "General Entertainment",
            "Gold" => "Gold",
            "Grocery Stores" => "Grocery Stores",
            "Health Care Plans" => "Health Care Plans",
            "Healthcare Information Services" => "Healthcare Information Services",
            "Heavy Construction" => "Heavy Construction",
            "Home Furnishing Stores" => "Home Furnishing Stores",
            "Home Furnishings & Fixtures" => "Home Furnishings and Fixtures",
            "Home Health Care" => "Home Health Care",
            "Home Improvement Stores" => "Home Improvement Stores",
            "Hospitals" => "Hospitals",
            "Housewares & Accessories" => "Housewares and Accessories",
            "Independent Oil & Gas" => "Independent Oil and Gas",
            "Industrial Electrical Equipment" => "Industrial Electrical Equipment",
            "Industrial Equipment & Components" => "Industrial Equipment and Components",
            "Industrial Equipment Wholesale" => "Industrial Equipment Wholesale",
            "Industrial Metals & Minerals" => "Industrial Metals and Minerals",
            "Information & Delivery Services" => "Information and Delivery Services",
            "Information Technology Services" => "Information Technology Services",
            "Insurance Brokers" => "Insurance Brokers",
            "Internet Information Providers" => "Internet Information Providers",
            "Internet Service Providers" => "Internet Service Providers",
            "Internet Software & Services" => "Internet Software and Services",
            "Investment Brokerage - National" => "Investment Brokerage - National",
            "Investment Brokerage - Regional" => "Investment Brokerage - Regional",
            "Jewelry Stores" => "Jewelry Stores",
            "Life Insurance" => "Life Insurance",
            "Lodging" => "Lodging",
            "Long Distance Carriers" => "Long Distance Carriers",
            "Long-Term Care Facilities" => "Long-Term Care Facilities",
            "Lumber, Wood Production" => "Lumber, Wood Production",
            "Machine Tools & Accessories" => "Machine Tools and Accessories",
            "Major Airlines" => "Major Airlines",
            "Major Integrated Oil & Gas" => "Major Integrated Oil and Gas",
            "Management Services" => "Management Services",
            "Manufactured Housing" => "Manufactured Housing",
            "Marketing Services" => "Marketing Services",
            "Meat Products" => "Meat Products",
            "Medical Appliances & Equipment" => "Medical Appliances and Equipment",
            "Medical Equipment Wholesale" => "Medical Equipment Wholesale",
            "Medical Instruments & Supplies" => "Medical Instruments and Supplies",
            "Medical Laboratories & Research" => "Medical Laboratories and Research",
            "Metal Fabrication" => "Metal Fabrication",
            "Money Center Banks" => "Money Center Banks",
            "Mortgage Investment" => "Mortgage Investment",
            "Movie Production, Theaters" => "Movie Production, Theaters",
            "Multimedia & Graphics Software" => "Multimedia and Graphics Software",
            "Music & Video Stores" => "Music and Video Stores",
            "Networking & Communication Devices" => "Networking and Communication Devices",
            "Nonmetallic Mineral Mining" => "Nonmetallic Mineral Mining",
            "Office Supplies" => "Office Supplies",
            "Oil & Gas Drilling & Exploration" => "Oil and Gas Drilling and Exploration",
            "Oil & Gas Equipment & Services" => "Oil and Gas Equipment and Services",
            "Oil & Gas Pipelines" => "Oil and Gas Pipelines",
            "Oil & Gas Refining & Marketing" => "Oil and Gas Refining and Marketing",
            "Packaging & Containers" => "Packaging and Containers",
            "Paper & Paper Products" => "Paper and Paper Products",
            "Personal Products" => "Personal Products",
            "Personal Services" => "Personal Services",
            "Photographic Equipment & Supplies" => "Photographic Equipment and Supplies",
            "Pollution & Treatment Controls" => "Pollution and Treatment Controls",
            "Printed Circuit Boards" => "Printed Circuit Boards",
            "Processed & Packaged Goods" => "Processed and Packaged Goods",
            "Processing Systems & Products" => "Processing Systems and Products",
            "Property & Casualty Insurance" => "Property and Casualty Insurance",
            "Property Management" => "Property Management",
            "Publishing - Books" => "Publishing - Books",
            "Publishing - Newspapers" => "Publishing - Newspapers",
            "Publishing - Periodicals" => "Publishing - Periodicals",
            "Railroads" => "Railroads",
            "Real Estate Development" => "Real Estate Development",
            "Recreational Goods, Other" => "Recreational Goods, Other",
            "Recreational Vehicles" => "Recreational Vehicles",
            "Regional - Mid-Atlantic Banks" => "Regional - Mid-Atlantic Banks",
            "Regional - Midwest Banks" => "Regional - Midwest Banks",
            "Regional - Northeast Banks" => "Regional - Northeast Banks",
            "Regional - Pacific Banks" => "Regional - Pacific Banks",
            "Regional - Southeast Banks" => "Regional - Southeast Banks",
            "Regional - Southwest  Banks" => "Regional - Southwest  Banks",
            "Regional - Southwest Banks" => "Regional - Southwest Banks",
            "Regional Airlines" => "Regional Airlines",
            "REIT - Diversified" => "REIT - Diversified",
            "REIT - Healthcare Facilities" => "REIT - Healthcare Facilities",
            "REIT - Hotel/Motel" => "REIT - Hotel/Motel",
            "REIT - Industrial" => "REIT - Industrial",
            "REIT - Office" => "REIT - Office",
            "REIT - Residential" => "REIT - Residential",
            "REIT - Retail" => "REIT - Retail",
            "Rental & Leasing Services" => "Rental and Leasing Services",
            "Research Services" => "Research Services",
            "Residential Construction" => "Residential Construction",
            "Resorts & Casinos" => "Resorts and Casinos",
            "Restaurants" => "Restaurants",
            "Rubber & Plastics" => "Rubber and Plastics",
            "Savings & Loans" => "Savings and Loans",
            "Scientific & Technical Instruments" => "Scientific and Technical Instruments",
            "Security & Protection Services" => "Security and Protection Services",
            "Security Software & Services" => "Security Software and Services",
            "Semiconductor - Broad Line" => "Semiconductor - Broad Line",
            "Semiconductor - Integrated Circuits" => "Semiconductor - Integrated Circuits",
            "Semiconductor - Specialized" => "Semiconductor - Specialized",
            "Semiconductor Equipment & Materials" => "Semiconductor Equipment and Materials",
            "Semiconductor- Memory Chips" => "Semiconductor- Memory Chips",
            "Shipping" => "Shipping",
            "Silver" => "Silver",
            "Small Tools & Accessories" => "Small Tools and Accessories",
            "Specialized Health Services" => "Specialized Health Services",
            "Specialty Chemicals" => "Specialty Chemicals",
            "Specialty Eateries" => "Specialty Eateries",
            "Specialty Retail, Other" => "Specialty Retail, Other",
            "Sporting Activities" => "Sporting Activities",
            "Sporting Goods" => "Sporting Goods",
            "Sporting Goods Stores" => "Sporting Goods Stores",
            "Staffing & Outsourcing Services" => "Staffing and Outsourcing Services",
            "Steel & Iron" => "Steel and Iron",
            "Surety & Title Insurance" => "Surety and Title Insurance",
            "Synthetics" => "Synthetics",
            "Technical & System Software" => "Technical and System Software",
            "Technical Services" => "Technical Services",
            "Telecom Services - Domestic" => "Telecom Services - Domestic",
            "Telecom Services - Foreign" => "Telecom Services - Foreign",
            "Textile - Apparel Clothing" => "Textile - Apparel Clothing",
            "Textile - Apparel Footwear & Accessories" => "Textile - Apparel Footwear and Accessories",
            "Textile Industrial" => "Textile Industrial",
            "Tobacco Products, Other" => "Tobacco Products, Other",
            "Toy & Hobby Stores" => "Toy and Hobby Stores",
            "Toys & Games" => "Toys and Games",
            "Trucking" => "Trucking",
            "Trucks & Other Vehicles" => "Trucks and Other Vehicles",
            "Waste Management" => "Waste Management",
            "Water Utilities" => "Water Utilities",
            "Wirel| Communications" => "Wirel| Communications"
        ],


//$sec
        'SECTOR' => [
            "Basic Materials" => "1",
            "Conglomerates" => "2",
            "Consumer Goods" => "3",
            "Financial" => "4",
            "Healthcare" => "5",
            "Industrial Goods" => "6",
            "Services" => "7",
            "Technology" => "8",
            "Utilities" => "9"
        ],


//$size

        'SIZE' => [
            "100" => "100",
            "200" => "200",
            "300" => "300",
            "400" => "400",
            "500" => "500",
            "700" => "700",
            "800" => "800",
            "900" => "900",
            "1000" => "1000",
            "1500" => "1500",
            "2000" => "2000"
        ],


//$price

        'PRICE' => [
            "$1" => "1",
            "$2" => "2",
            "$3" => "3",
            "$4" => "4",
            "$5" => "5",
            "$7" => "7",
            "$8" => "8",
            "$9" => "9",
            "$10" => "10",
            "$15" => "15",
            "$20" => "20",
            "$30" => "30",
            "$40" => "40",
            "$50" => "50",
            "$60" => "60",
            "$70" => "70",
            "$80" => "80",
            "$90" => "90",
            "$100" => "100",
            "$110" => "110",
            "$120" => "120",
            "$130" => "130",
            "$150" => "150",
        ],


//$avvo
        'AVVO' => [
            "50K" => "50",
            "100K" => "100",
            "150K" => "150",
            "200K" => "200",
            "300K" => "300",
            "400K" => "400",
            "500K" => "500",
            "600K" => "600",
            "700K" => "700",
            "800K" => "800",
            "900K" => "900",
            "1M" => "1000",
            "2M" => "2000",
            "3M" => "3000",
            "4M" => "4000",
            "5M" => "5000",
            "6M" => "6000",
            "10M" => "10000",
        ],


//$atr

        'ATR' => [
            "Any" => "",
            "Over 0.10" => "m|0.10",
            "Over 0.25" => "m|0.25",
            "Over 0.5" => "m|0.5",
            "Over 0.75" => "m|0.75",
            "Over 1" => "m|1",
            "Over 1.5" => "m|1.5",
            "Over 2" => "m|2",
            "Over 2.5" => "m|2.5",
            "Over 3" => "m|3",
            "Over 3.5" => "m|3.5",
            "Over 4" => "m|4",
            "Over 4.5" => "m|4.5",
            "Over 5" => "m|5",
            "Under 0.10" => "l|0.10",
            "Under 0.25" => "l|0.25",
            "Under 0.5" => "l|0.5",
            "Under 0.75" => "l|0.75",
            "Under 1" => "l|1",
            "Under 1.5" => "l|1.5",
            "Under 2" => "l|2",
            "Under 2.5" => "l|2.5",
            "Under 3" => "l|3",
            "Under 3.5" => "l|3.5",
            "Under 4" => "l|4",
            "Under 4.5" => "l|4.5",
            "Under 5" => "l|5",
        ],


//$change
        'CHANGE' => [
            "Any" => "",
            "Up" => "m|0",
            "Up 1%" => "m|1",
            "Up 2%" => "m|2",
            "Up 3%" => "m|3",
            "Up 4%" => "m|4",
            "Up 5%" => "m|5",
            "Up 6%" => "m|6",
            "Up 7%" => "m|7",
            "Up 8%" => "m|8",
            "Up 9%" => "m|9",
            "Up 10%" => "m|10",
            "Up 15%" => "m|15",
            "Up 20%" => "m|20",
            "Up 50%" => "m|50",
            "Down" => "l|0",
            "Down 1%" => "l|-1",
            "Down 2%" => "l|-2",
            "Down 3%" => "l|-3",
            "Down 4%" => "l|-4",
            "Down 5%" => "l|-5",
            "Down 6%" => "l|-6",
            "Down 7%" => "l|-7",
            "Down 8%" => "l|-8",
            "Down 9%" => "l|-9",
            "Down 10%" => "l|-10",
            "Down 15%" => "l|-15",
            "Down 20%" => "l|-20",
            "Down 50%" => "l|-50",
        ],


//$toprice
        'TO_PRICE' => [
            "Any" => "",
            "Above $$" => "m|0",
            "1% or more above $$" => "m|1",
            "2% or more above $$" => "m|2",
            "3% or more above $$" => "m|3",
            "4% or more above $$" => "m|4",
            "5% or more above $$" => "m|5",
            "6% or more above $$" => "m|6",
            "7% or more above $$" => "m|7",
            "8% or more above $$" => "m|8",
            "9% or more above $$" => "m|9",
            "10% or more above $$" => "m|10",
            "15% or more above $$" => "m|15",
            "20% or more above $$" => "m|20",
            "50% or more above $$" => "m|50",
            "Below $$$" => "l|0",
            "1% or more below $$" => "l|-1",
            "2% or more below $$" => "l|-2",
            "3% or more below $$" => "l|-3",
            "4% or more below $$" => "l|-4",
            "5% or more below $$" => "l|-5",
            "6% or more below $$" => "l|-6",
            "7% or more below $$" => "l|-7",
            "8% or more below $$" => "l|-8",
            "9% or more below $$" => "l|-9",
            "10% or more below $$" => "l|-10",
            "15% or more below $$" => "l|-15",
            "20% or more below $$" => "l|-20",
            "50% or more below $$" => "l|-50",
        ],


//$toprice_b
        'TO_PRICE_BELOW' => [
            "Any" => "",
            "0-1% below $$" => "l|1",
            "0-3% below $$" => "l|3",
            "0-5% below $$" => "l|5",
            "5% or more below $$" => "m|5",
            "6% or more below $$" => "m|6",
            "7% or more below $$" => "m|7",
            "3% or more below $$" => "m|3",
            "8% or more below $$" => "m|8",
            "9% or more below $$" => "m|9",
            "10% or more below $$" => "m|10",
            "15% or more below $$" => "m|15",
            "20% or more below $$" => "m|20",
            "50% or more below $$" => "m|50",
        ],

//$toprice_a
        'TO_PRICE_ABOVE' => [
            "Any" => "",
            "0-1% above $$" => "l|1",
            "0-3% above $$" => "l|3",
            "0-5% above $$" => "l|5",
            "5% or more above $$" => "m|5",
            "6% or more above $$" => "m|6",
            "7% or more above $$" => "m|7",
            "3% or more above $$" => "m|3",
            "8% or more above $$" => "m|8",
            "9% or more above $$" => "m|9",
            "10% or more above $$" => "m|10",
            "15% or more above $$" => "m|15",
            "20% or more above $$" => "m|20",
            "50% or more above $$" => "m|50"
        ],


//$vol
        'VOLUME' => [
            "10K" => "10000",
            "20K" => "20000",
            "50K" => "50000",
            "100K" => "100000",
            "150K" => "150000",
            "200K" => "200000",
            "300K" => "300000",
            "400K" => "400000",
            "500K" => "500000",
            "750K" => "750000",
            "1M" => "1000000",
            "2M" => "2000000",
            "3M" => "3000000",
            "4M" => "4000000",
            "5M" => "5000000",
            "10M" => "10000000",
            "20M" => "20000000",
        ],


//$mc
        'MARKET_CAP' => [
            "50M" => "50",
            "100M" => "100",
            "200M" => "200",
            "300M" => "300",
            "500M" => "500",
            "1B" => "1000",
            "2B" => "2000",
            "5B" => "5000",
            "10B" => "10000",
            "50B" => "50000",
            "100B" => "100000",
            "200B" => "200000"
        ],


//$index

        'INDEX' => [
            "Any" => "",
            "DJIA" => "m|1",
            "S&P 500" => "m|0",
            "все кроме S&P 500" => "l|1",
        ],


//$changed

        'CHANGED' => [
            "Any" => "",
            "Up" => "m|0",
            "Up 0.1$" => "m|0.1",
            "Up 0.2$" => "m|0.2",
            "Up 0.3$" => "m|0.3",
            "Up 0.4$" => "m|0.4",
            "Up 0.5$" => "m|0.5",
            "Up 0.7$" => "m|0.7",
            "Up 1$" => "m|1",
            "Up 1.5$" => "m|1.5",
            "Up 2$" => "m|2",
            "Up 3$" => "m|3",
            "Up 4$" => "m|4",
            "Up 5$" => "m|5",
            "Up 7$" => "m|7",
            "Up 8$" => "m|8",
            "Up 9$" => "m|9",
            "Up 10$" => "m|10",
            "Up 15$" => "m|15",
            "Up 20$" => "m|20",
            "Down" => "l|0",
            "Down 0.1$" => "l|-0.1",
            "Down 0.2$" => "l|-0.2",
            "Down 0.3$" => "l|-0.3",
            "Down 0.4$" => "l|-0.4",
            "Down 0.5$" => "l|-0.5",
            "Down 0.7$" => "l|-0.7",
            "Down 1$" => "l|-1",
            "Down 1.5$" => "l|-1.5",
            "Down 2$" => "l|-2",
            "Down 3$" => "l|-3",
            "Down 4$" => "l|-4",
            "Down 5$" => "l|-5",
            "Down 6$" => "l|-6",
            "Down 7$" => "l|-7",
            "Down 8$" => "l|-8",
            "Down 9$" => "l|-9",
            "Down 10$" => "l|-10",
            "Down 20$" => "l|-20",
        ],


//$revol

        'RELATIVE_VOL' => [
            "0.1" => "0.1",
            "0.2" => "0.2",
            "0.3" => "0.3",
            "0.4" => "0.4",
            "0.5" => "0.5",
            "0.6" => "0.6",
            "0.7" => "0.7",
            "0.8" => "0.8",
            "0.9" => "0.9",
            "1" => "1",
            "1.3" => "1.3",
            "1.5" => "1.5",
            "2" => "2",
            "3" => "3",
            "5" => "5",
            "10" => "10",
            "20" => "20",
            "50" => "50",
            "100" => "100",
        ],


//$exchange =
        'EXCHANGE' => [
            "NYSE" => "1",
            "NASDAQ" => "2",
            "AMEX" => "3",
            "NYSEARCA (ETF)" => "4",
            "BATS (ETF)" => "6"
        ],


//$pe
        'PE' => [
            "Any" => "",
            "Under 5" => "l|5",
            "Under 10" => "l|10",
            "Under 15" => "l|15",
            "Under 20" => "l|20",
            "Under 25" => "l|25",
            "Under 30" => "l|30",
            "Under 35" => "l|35",
            "Under 40" => "l|40",
            "Under 45" => "l|45",
            "Under 50" => "l|50",
            "Under 100" => "l|100",
            "Under 500" => "l|500",
            "Over 5" => "m|5",
            "Over 10" => "m|10",
            "Over 15" => "m|15",
            "Over 20" => "m|20",
            "Over 25" => "m|25",
            "Over 30" => "m|30",
            "Over 35" => "m|35",
            "Over 40" => "m|40",
            "Over 45" => "m|45",
            "Over 50" => "m|50",
            "Over 100" => "m|100",
            "Over 500" => "m|500",
        ],


//$eps
        'EPS' => [
            "Any" => "",
            "Under 0" => "l|0",
            "Under 1" => "l|1",
            "Under 2" => "l|2",
            "Under 3" => "l|3",
            "Under 4" => "l|4",
            "Under 5" => "l|5",
            "Under 10" => "l|10",
            "Under 15" => "l|15",
            "Under" => "m|20",
            "Under 25" => "l|25",
            "Under 30" => "l|30",
            "Over 0" => "m|0",
            "Over 1" => "m|1",
            "Over 2" => "m|2",
            "Over 3" => "m|3",
            "Over 4" => "m|4",
            "Over 5" => "m|5",
            "Over 10" => "m|10",
            "Over 15" => "m|15",
            "Over 20" => "m|20",
            "Over 25" => "m|25",
            "Over 30" => "m|30",
        ],


//$aut
        'AUT' => [
            "100K" => "0.1",
            "500K" => "0.5",
            "1M" => "1",
            "2M" => "2",
            "5M" => "5",
            "10M" => "10",
            "20M" => "20",
            "50M" => "50",
            "100M" => "100",
            "300M" => "300",
            "500M" => "500",
            "1B" => "1000",
            "10B" => "10000",
        ],


//$fshort
        'FLOAT_SHORT' => [
            "Any" => "",
            "Under 0%" => "l|0",
            "Under 1%" => "l|1",
            "Under 2%" => "l|2",
            "Under 3%" => "l|3",
            "Under 4%" => "l|4",
            "Under 5%" => "l|5",
            "Under 10%" => "l|10",
            "Under 15%" => "l|15",
            "Under 20%" => "l|20",
            "Under 25%" => "l|25",
            "Under 30%" => "l|30",
            "Over 0%" => "m|0",
            "Over 1%" => "m|1",
            "Over 2%" => "m|2",
            "Over 3%" => "m|3",
            "Over 4%" => "m|4",
            "Over 5%" => "m|5",
            "Over 10%" => "m|10",
            "Over 15%" => "m|15",
            "Over 20%" => "m|20",
            "Over 25%" => "m|25",
            "Over 30%" => "m|30",
        ],


//$shratio

        'SHORT_RATIO' => [
            "Any" => "",
            "Under 0.5" => "l|0.5",
            "Under 1" => "l|1",
            "Under 2" => "l|2",
            "Under 3" => "l|3",
            "Under 4" => "l|4",
            "Under 5" => "l|5",
            "Under 10" => "l|10",
            "Over 0.5" => "m|0.5",
            "Over 1" => "m|1",
            "Over 2" => "m|2",
            "Over 3" => "m|3",
            "Over 4" => "m|4",
            "Over 5" => "m|5",
            "Over 10" => "m|10",
            "Over 15" => "m|15",
            "Over 20" => "m|20",
            "Over 25" => "m|25",
            "Over 30" => "m|30",
        ],

//$float
        'SHARE_FLOAT' => [
            "100K" => "0.1",
            "500K" => "0.5",
            "1M" => "1",
            "2M" => "2",
            "5M" => "5",
            "10M" => "10",
            "20M" => "20",
            "50M" => "50",
            "100M" => "100",
            "300M" => "300",
            "500M" => "500",
            "1B" => "1000",
            "10B" => "10000",
        ],

//$tcount

        'TRADE_COUNT' => [
            "Any" => "",
            "Under 100 000" => "l|100000",
            "Under 50 000" => "l|50000",
            "Under 10 000" => "l|10000",
            "Under 5 000" => "l|5000",
            "Under 500" => "l|500",
            "Under 50" => "l|50",
            "Over 0" => "m|0",
            "Over 10" => "m|10",
            "Over 50" => "m|50",
            "Over 100" => "m|100",
            "Over 500" => "m|500",
            "Over 1000" => "m|1000",
            "Over 5000" => "m|5000",
            "Over 10 000" => "m|10000",
            "Over 25 000" => "m|25000",
            "Over 100 000" => "m|100000"
        ],


//$percent
        'PERCENT' => [
            "0%" => "0",
            "1%" => "1",
            "2%" => "2",
            "3%" => "3",
            "4%" => "4",
            "5%" => "5",
            "6%" => "6",
            "7%" => "7",
            "8%" => "8",
            "9%" => "9",
            "10%" => "10",
            "15%" => "15",
            "20%" => "20",
            "50%" => "50",
            "-1%" => "-1",
            "-2%" => "-2",
            "-3%" => "-3",
            "-4%" => "-4",
            "-5%" => "-5",
            "-6%" => "-6",
            "-7%" => "-7",
            "-8%" => "-8",
            "-9%" => "-9",
            "-10%" => "-10",
            "-15%" => "-15",
            "-20%" => "-20",
            "-50%" => "-50",
        ],


// $pluspercent
        'PLUS_PERCENT' => [
            "1%" => "1",
            "2%" => "2",
            "3%" => "3",
            "5%" => "5",
            "10%" => "10",
            "15%" => "15",
            "20%" => "20",
            "50%" => "50",
            "60%" => "50",
            "70%" => "50",
            "80%" => "50",
            "90%" => "50"
        ],


//$coun

        'COUNTRY' => [
            "Any" => "",
            "Argentina" => "Argentina",
            "Australia" => "Australia",
            "Bahamas" => "Bahamas",
            "Belgium" => "Belgium",
            "Bermuda" => "Bermuda",
            "Brazil" => "Brazil",
            "British Virgin Islands" => "British Virgin Islands",
            "Canada" => "Canada",
            "Cayman Islands" => "Cayman Islands",
            "Channel Islands" => "Channel Islands",
            "Chile" => "Chile",
            "China" => "China",
            "Colombia" => "Colombia",
            "Cyprus" => "Cyprus",
            "Denmark" => "Denmark",
            "Finland" => "Finland",
            "France" => "France",
            "Germany" => "Germany",
            "Greece" => "Greece",
            "Hong Kong" => "Hong Kong",
            "India" => "India",
            "Indonesia" => "Indonesia",
            "Ireland" => "Ireland",
            "Israel" => "Israel",
            "Italy" => "Italy",
            "Japan" => "Japan",
            "Luxembourg" => "Luxembourg",
            "Mexico" => "Mexico",
            "Monaco" => "Monaco",
            "Netherlands" => "Netherlands",
            "Netherlands Antilles" => "Netherlands Antilles",
            "Norway" => "Norway",
            "Panama" => "Panama",
            "Peru" => "Peru",
            "Philippines" => "Philippines",
            "Portugal" => "Portugal",
            "Russia" => "Russia",
            "Singapore" => "Singapore",
            "South Africa" => "South Africa",
            "South Korea" => "South Korea",
            "Spain" => "Spain",
            "Sweden" => "Sweden",
            "Switzerland" => "Switzerland",
            "Taiwan" => "Taiwan",
            "Turkey" => "Turkey",
            "United Kingdom" => "United Kingdom",
            "USA" => "USA"
        ],
    ];

    const  OPERATOR_CUSTOM_VALUES = [
        'sizeex' => [
            '1' => 'bid>= hi AND hi!=0',
            '2' => 'bid<=lo AND lo!=0',
            '3' => 'ask>=hi AND hi!=0',
            '4' => 'ask<=lo AND lo!=0'
        ],
        'runup' => [
            '1' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END) >10',
            '2' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END) >10',
            '3' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END) >25',
            '4' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END) >25',
            '5' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END) >50',
            '6' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END) >50',
            '7' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END) >70',
            '8' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END) >70',
            '9' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END) >90',
            '10' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END) >90',
            '11' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END) >10',
            '12' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END) >10',
            '13' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END) >25',
            '14' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END) >25',
            '15' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END) >50',
            '16' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END) >50',
            '17' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END) >70',
            '18' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((price-price51m)/(l.hi-l.lo))*100 END) >70',
            '19' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END) >90',
            '20' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END) >90',
            '21' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END) >10',
            '22' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END) >10',
            '23' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END) >25',
            '24' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END) >25',
            '25' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END) >50',
            '26' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END) >50',
            '27' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END) >70',
            '28' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END) >70',
            '29' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END) >90',
            '30' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END) >90',
            '31' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END) >10',
            '32' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END) >10',
            '33' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END) >25',
            '34' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END) >25',
            '35' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END) >50',
            '36' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END) >50',
            '37' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END) >70',
            '38' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END) >70',
            '39' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END) >90',
            '40' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END) >90',
        ],
        'rundown' => [
            '1' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END)<-10',
            '2' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END)<-10',
            '3' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END)<-25',
            '4' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END)<-25',
            '5' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END)<-50',
            '6' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END)<-50',
            '7' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END)<-70',
            '8' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END)<-70',
            '9' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/b.atr)*100 END)<-90',
            '10' => '(CASE WHEN m.price1m=0 THEN 0 ELSE ((l.price-m.price1m)/(l.hi-l.lo))*100 END)<-90',
            '11' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END)<-10',
            '12' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END)<-10',
            '13' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END)<-25',
            '14' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END)<-25',
            '15' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END)<-50',
            '16' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END)<-50',
            '17' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END)<-70',
            '18' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END)<-70',
            '19' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/b.atr)*100 END)<-90',
            '20' => '(CASE WHEN m.price5m=0 THEN 0 ELSE ((l.price-m.price5m)/(l.hi-l.lo))*100 END)<-90',
            '21' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END)<-10',
            '22' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END)<-10',
            '23' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END)<-25',
            '24' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END)<-25',
            '25' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END)<-50',
            '26' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END)<-50',
            '27' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END)<-70',
            '28' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END)<-70',
            '29' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/b.atr)*100 END)<-90',
            '30' => '(CASE WHEN m.price10m=0 THEN 0 ELSE ((l.price-m.price10m)/(l.hi-l.lo))*100 END)<-90',
            '31' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END)<-10',
            '32' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END)<-10',
            '33' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END)<-25',
            '34' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END)<-25',
            '35' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END)<-50',
            '36' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END)<-50',
            '37' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END)<-70',
            '38' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END)<-70',
            '39' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/b.atr)*100 END)<-90',
            '40' => '(CASE WHEN m.price15m=0 THEN 0 ELSE ((l.price-m.price15m)/(l.hi-l.lo))*100 END)<-90',
        ],
        'unsize' => [
            '1' => "l.bidsize / l.asksize >6 AND ((l.bidsize >=100 AND b.avvo < 1000) OR (l.bidsize >= 200 AND b.avvo > 1000  AND b.avvo < 5000) OR (l.bidsize >=500 AND b.avvo > 5000) )",
            '2' => "l.asksize / l.bidsize >6 AND ((l.asksize >=100 AND b.avvo < 1000) OR (l.asksize >= 200 AND b.avvo > 1000 AND b.avvo < 5000) OR (l.asksize >=500 AND b.avvo > 5000) )",

        ],
        'newhilo' => [
            '1' => '(l.hi-l.price)=0',
            '2' => '(l.price-l.lo)=0',
            '3' => '(l.hi-l.price)<=0.01',
            '4' => '(l.hi-l.price)<=0.02',
            '5' => '(l.hi-l.price)<=0.03',
            '6' => '(l.hi-l.price)<=0.05',
            '7' => '(l.hi-l.price)<=0.1',
            '8' => '(l.price-l.lo)<=0.01',
            '9' => '(l.price-l.lo)<=0.02',
            '10' => '(l.price-l.lo)<=0.03',
            '11' => '(l.price-l.lo)<=0.05',
            '12' => '(l.price-l.lo)<=0.1',
        ],
        'fig' => [
            '1' => '(l.price%1)=0',
            '2' => '(l.price%1)=0.50',
            '3' => '(l.price%1) IN(0.50,0)',
            '4' => '(l.price%1) IN(0,0.99,0.01)',
            '5' => '((l.price%1) <= 0.02 OR (l.price%1) >= 0.98)',
            '6' => '((l.price%1) <= 0.03 OR (l.price%1) >= 0.97)',
            '7' => '((l.price%1) <= 0.05 OR (l.price%1) >= 0.95)',
            '8' => '((l.price%1) <= 0.1 OR (l.price%1) >= 0.9)',
            '9' => '(l.price%1) IN(0.5,0.49,0.51)',
            '10' => '(l.price%1) BETWEEN 0.48 AND 0.52',
            '11' => '(l.price%1) BETWEEN 0.47 AND 0.53',
            '12' => '(l.price%1) BETWEEN 0.45 AND 0.55',
            '13' => '(l.price%1) IN(0.5,0.49,0.51,0,0.99,0.01)',
            '14' => '((l.price%1) BETWEEN 0.48 AND 0.52 OR ((l.price%1) <= 0.02 OR (l.price%1) >= 0.98))',
            '15' => '((l.price%1) BETWEEN 0.47 AND 0.53 OR ((l.price%1) <= 0.03 OR (l.price%1) >= 0.97))',
            '16' => '((l.price%1) BETWEEN 0.45 AND 0.55 OR ((l.price%1) <= 0.05 OR (l.price%1) >= 0.95))'


        ]
    ];
}

