<?php

namespace ConsoleBundle\Repository\Premarket;

/**
 * IqfeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IqfeedRepository extends \Doctrine\ORM\EntityRepository
{
}
