<?php

namespace ConsoleBundle\Repository\Basic;

/**
 * IpoDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpoDateRepository extends \Doctrine\ORM\EntityRepository
{
}
