<?php

namespace AppBundle\Repository\Presets;

/**
 * UserChartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChartsRepository extends \Doctrine\ORM\EntityRepository
{

}
