<?php

namespace AppBundle\Repository\Presets;

/**
 * ColumnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColumnsRepository extends \Doctrine\ORM\EntityRepository
{
}
