<?php

namespace AppBundle\Repository\Presets;

/**
 * UsersFiltersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiltersRepository extends \Doctrine\ORM\EntityRepository
{
}
