<?php

namespace ConsoleBundle\Repository\Tickers;

/**
 * AllListedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllListedRepository extends \Doctrine\ORM\EntityRepository
{
}
