<?php

namespace ConsoleBundle\Repository\Tickers;

/**
 * NasdaqListedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NasdaqListedRepository extends \Doctrine\ORM\EntityRepository
{
}
