<?php

namespace ConsoleBundle\Repository\Tickers;

/**
 * OtherListedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherListedRepository extends \Doctrine\ORM\EntityRepository
{
}
