<?php

namespace ConsoleBundle\Repository\Charts;

/**
 * DailyCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyCounterRepository extends \Doctrine\ORM\EntityRepository
{
}
