<?php

namespace ConsoleBundle\Repository\Charts;

/**
 * DailyHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
